// <auto-generated />
namespace ProducerVerification.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update1ProducerUserInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1ProducerUserInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201705171917049_Update1ProducerUserInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
